version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: websecservice
    container_name: websecservice
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - websecservice

  db:
    image: mysql:8.0
    container_name: websecservice_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: websecservice
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
      MYSQL_USER: user
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - websecservice

  nginx:
    image: nginx:alpine
    container_name: websecservice_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - websecservice

networks:
  websecservice:
    driver: bridge

volumes:
  dbdata: 